### ISSUE TITLE
what's this ?

### ISSUE THREAD

**Issue by RottenLeader** [Acetolyne/portapack-carnage#22]
a new firmware ?

**Comment by Acetolyne** [comment]
The readme us clear that it is firmware and the very first line in the readme suggests that noone uses it 

`If you want the most active repository for your portapack use the Mayhem repo. This repo is a fork and is still under development with some very unstable code.`

The project is going to be a rewritten firmware with a new UI that makes it easier for developers however the project needed to go to the backburner for a while due to the number of other projects that I have at this time.
